# Generated by Django 2.2.7 on 2020-07-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='desription',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
