# Generated by Django 2.2.7 on 2020-07-11 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20200711_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
