# Generated by Django 2.2.7 on 2020-07-12 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_auto_20200711_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.Service')),
            ],
        ),
    ]
