# Generated by Django 2.2.7 on 2020-07-12 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_job_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_service',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job'),
        ),
    ]
