# Generated by Django 2.2.7 on 2020-07-12 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_auto_20200712_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_service',
            name='userId',
        ),
        migrations.AlterField(
            model_name='job_service',
            name='jobId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job'),
        ),
    ]
